[pytest]
# Look for tests only in a 'tests' folder or the current directory
testpaths = main/tests

# Ignore the virtual environment directory
norecursedirs = venv .git .vscode Lib site-packages __pycache__

# Explicitly ignore the venv folder during collection
addopts = -v --ignore=venv